### ISSUE TITLE
How to get it to work?

### ISSUE THREAD

**Issue by chrabia** [cdloh/obsidian-cron#3]
Amazing plugin! But...
![Screenshot_2023-04-24-22-22-42-950_md obsidian](https://user-images.githubusercontent.com/6050673/234108131-935cd0ea-2dd5-4cca-8e2d-861a959c9fa6.jpg)
I set this up. It's not working at all, whatever I try to do, nothing happens. The only plugins I have enabled right now are: obsidian tasks, obsidian git and obsidian home. Screenshot is from the mobile, but it's not working on my Macbook too.
Also, what is "Cron Interval" exactly for?

**Comment by chrabia** [comment]
Oh, of course unlocking the padlock is not helping.
What I didn't know is that I need to check the third button too and also wait a bit, as it's not running exactly at the time, but after ~10 seconds.
Still didn't manage to make it work on MacBook, I'll look into that later today.

**Comment by chrabia** [comment]
Ok, I don't know why, but it started working on my macbook too. I will enable all other plugins, maybe some of them were messing with it before, I will let you know.

Still, it would be nice to know what is "Cron Interval" exactly for.

**Comment by cdloh** [comment]
Hi @chrabia 👋 

Obsidian CRON isn't a true cron. It doesn't constantly run and fully respect your cron schedule. Instead what it does is that it runs on an interval (that you set in that interval setting) and on each run it then checks if there are any jobs that are meant to have been run since the last interval.

So if you have a job that runs every minute, but the cron is only setup to run on a 15 minute interval the job will only run once every 15 minutes.

Hope this explains it!

If you find any bugs please feel free to log them!

Ps I pushed a fix a day or two ago for an issue with the padlock / locking feature see #2

**Comment by cdloh** [comment]
Hopefully that answers your question!

**Comment by chrabia** [comment]
Yup, that explains a lot! Thanks!
I guess the problems I had might have been might have been connected to #2
Thanks again for this great plugin!
