### ISSUE TITLE
can'not read properties of undefined (reading 'locked')  

### ISSUE THREAD

**Issue by lifesign** [cdloh/obsidian-cron#4]
i added two cron job, but when i delete one of them, the last cron job will not work

## error in console
![image](https://github.com/cdloh/obsidian-cron/assets/2189610/534a9772-1102-4291-a131-033c02dfa144)

## cron setting
![image](https://github.com/cdloh/obsidian-cron/assets/2189610/16117532-dfba-44b8-b6a9-071f42598479)

## data.json
![image](https://github.com/cdloh/obsidian-cron/assets/2189610/808299aa-f12b-463b-a514-ce93ae15f3fe)

**Comment by lifesign** [comment]
Another issue is in cron settings,  `periodic-notes:next-daily-note` command is available, but when executed this command by cron, i got the wrong date note opened.

and also in Command Palette only `open daily note` supported
![image](https://github.com/cdloh/obsidian-cron/assets/2189610/31c4b2c5-1cf8-430a-8c7b-e8b6bde5cc83)

**Comment by cdloh** [comment]
Periodic notes open commands use the current active file to pick the next daily note so there isn't anything I can do there for picking the right file I'm afraid.

Also the commands will only appear if they are available. Since Periodic Notes use checks to see if the commands are available in that context they won't appear. See - https://github.com/liamcain/obsidian-periodic-notes/blob/0.0.17/src/commands.ts#L160-L165

---

Re the bug if you toggle the lock manually in the settings does that fix it? I can't reproduce it on my end.

Are you able to fix it and then reproduce it again?

**Comment by lifesign** [comment]
Reproduce
1. disable & enable cron plugin, make it refresh
2. set `Cron Interval` to 1 miniute
3. Add cron job 1, name: T1, command: periodic-notes:open-daily cron: * * * * *
4. Add cron job 2, name: T2 command: calendar:show-calendar-view cron: * * * * *
5. open developer console, wait for the first trigger, ok
6. delete T2 job, wait for the next round.

you got the error
![image](https://github.com/cdloh/obsidian-cron/assets/2189610/938376c4-ca65-442e-abd3-69e4503591c3)

**Comment by cdloh** [comment]
Whoops sorry didn't mean to close this. Can you test 1.1.2 and see if it fixes it for you?

**Comment by lifesign** [comment]
fixed~, thx~
